// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"
	"github.com/zkw/mini-schedule/backend/internal/application/commercial"
	"github.com/zkw/mini-schedule/backend/internal/application/course"
	"github.com/zkw/mini-schedule/backend/internal/application/learnerbooking"
	"github.com/zkw/mini-schedule/backend/internal/application/training"
	"github.com/zkw/mini-schedule/backend/internal/application/user"
	"github.com/zkw/mini-schedule/backend/internal/infrastructure/cache"
	"github.com/zkw/mini-schedule/backend/internal/infrastructure/config"
	"github.com/zkw/mini-schedule/backend/internal/infrastructure/persistence"
	"github.com/zkw/mini-schedule/backend/internal/interfaces/app"
	"github.com/zkw/mini-schedule/backend/internal/interfaces/middleware"
	"gorm.io/gorm"
	"log/slog"
)

// Injectors from wire.go:

// initializeAppApp C 端依赖注入
func initializeAppApp(cfg *config.Config, log *slog.Logger) (*gin.Engine, func(), error) {
	databaseConfig := provideDatabaseConfig(cfg)
	db, err := persistence.NewDatabase(databaseConfig, log)
	if err != nil {
		return nil, nil, err
	}
	appUserRepository := persistence.NewAppUserRepository(db)
	appUserService := user.NewAppUserService(appUserRepository, cfg)
	repository := persistence.NewCourseRepository(db)
	service := course.NewService(repository, cfg)
	trainingRepository := persistence.NewTrainingRepository(db)
	trainingService := training.NewService(trainingRepository, cfg)
	jwtConfig := provideJWTConfig(cfg)
	cacheService := cache.NewService(jwtConfig)
	bookingRepository := persistence.NewBookingRepository(db)
	classSessionRepository := persistence.NewClassSessionRepository(db)
	subscriptionGuard := commercial.NewSubscriptionGuard()
	learnerRepository := persistence.NewLearnerRepository(db, subscriptionGuard)
	entitlementRepository := persistence.NewEntitlementRepository(db)
	waitlistRepository := persistence.NewWaitlistRepository(db)
	learnerBookingService := learnerbooking.NewService(bookingRepository, classSessionRepository, entitlementRepository, waitlistRepository)
	handler := app.NewHandler(appUserService, service, trainingService, cacheService, learnerRepository, learnerBookingService)
	redisConfig := provideRedisConfig(cfg)
	client, err := cache.NewRedisClient(redisConfig, log)
	if err != nil {
		return nil, nil, err
	}
	engine := newAppRouter(handler, db, client, cacheService, cfg, log)
	return engine, func() {
	}, nil
}

// wire.go:

func provideDatabaseConfig(cfg *config.Config) *config.DatabaseConfig {
	return &cfg.Database
}

func provideRedisConfig(cfg *config.Config) *config.RedisConfig {
	return &cfg.Redis
}

func provideJWTConfig(cfg *config.Config) *config.JWTConfig {
	return &cfg.JWT
}

func newAppRouter(
	h *app.Handler,
	db *gorm.DB,
	redisClient *redis.Client,
	jwtSvc *cache.Service,
	cfg *config.Config,
	log *slog.Logger,
) *gin.Engine {
	gin.SetMode(gin.ReleaseMode)
	if cfg.App.Debug {
		gin.SetMode(gin.DebugMode)
	}

	r := gin.New()
	r.Use(middleware.Locale())
	r.Use(middleware.CORS(cfg.CORS))
	r.Use(gin.Recovery())

	api := r.Group("/api/v1/app")
	h.RegisterRoutes(api)

	return r
}
