// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/zkw/mini-schedule/backend/internal/application/brand"
	"github.com/zkw/mini-schedule/backend/internal/application/commercial"
	"github.com/zkw/mini-schedule/backend/internal/application/user"
	"github.com/zkw/mini-schedule/backend/internal/infrastructure/cache"
	"github.com/zkw/mini-schedule/backend/internal/infrastructure/config"
	"github.com/zkw/mini-schedule/backend/internal/infrastructure/persistence"
	"github.com/zkw/mini-schedule/backend/internal/interfaces/admin"
	"github.com/zkw/mini-schedule/backend/internal/interfaces/middleware"
	"gorm.io/gorm"
	"log/slog"
)

// Injectors from wire.go:

// initializeAdminApp 管理端依赖注入
func initializeAdminApp(cfg *config.Config, log *slog.Logger) (*gin.Engine, func(), error) {
	databaseConfig := provideDatabaseConfig(cfg)
	db, err := persistence.NewDatabase(databaseConfig, log)
	if err != nil {
		return nil, nil, err
	}
	repository := persistence.NewBrandRepository(db)
	service := brand.NewService(repository, cfg)
	commercialRepository := persistence.NewCommercialRepository(db)
	commercialService := commercial.NewService(commercialRepository, cfg)
	adminUserRepository := persistence.NewAdminUserRepository(db)
	jwtConfig := provideJWTConfig(cfg)
	cacheService := cache.NewService(jwtConfig)
	adminUserService := user.NewAdminUserService(adminUserRepository, cacheService, log, cfg)
	handler := admin.NewHandler(service, commercialService, adminUserService, cacheService)
	redisConfig := provideRedisConfig(cfg)
	client, err := cache.NewRedisClient(redisConfig, log)
	if err != nil {
		return nil, nil, err
	}
	engine := newAdminRouter(handler, db, client, cacheService, cfg, log)
	return engine, func() {
	}, nil
}

// wire.go:

func provideDatabaseConfig(cfg *config.Config) *config.DatabaseConfig {
	return &cfg.Database
}

func provideRedisConfig(cfg *config.Config) *config.RedisConfig {
	return &cfg.Redis
}

func provideJWTConfig(cfg *config.Config) *config.JWTConfig {
	return &cfg.JWT
}

func newAdminRouter(
	h *admin.Handler,
	db *gorm.DB,
	redisClient *redis.Client,
	jwtSvc *cache.Service,
	cfg *config.Config,
	log *slog.Logger,
) *gin.Engine {
	gin.SetMode(gin.ReleaseMode)
	if cfg.App.Debug {
		gin.SetMode(gin.DebugMode)
	}

	r := gin.New()
	r.Use(middleware.CORS(cfg.CORS))
	r.Use(middleware.Locale())
	r.Use(gin.Recovery())

	// Swagger UI（仅 debug 模式）
	if cfg.App.Debug {
		r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	}

	publicAPI := r.Group("/api/v1/public")
	h.RegisterPublicRoutes(publicAPI)

	api := r.Group("/api/v1/admin")
	h.RegisterRoutes(api)

	return r
}
