// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"
	"github.com/zkw/mini-schedule/backend/internal/application/booking"
	"github.com/zkw/mini-schedule/backend/internal/application/brand"
	"github.com/zkw/mini-schedule/backend/internal/application/brandprofile"
	"github.com/zkw/mini-schedule/backend/internal/application/classsession"
	"github.com/zkw/mini-schedule/backend/internal/application/commercial"
	"github.com/zkw/mini-schedule/backend/internal/application/coursecategory"
	"github.com/zkw/mini-schedule/backend/internal/application/coursetemplate"
	"github.com/zkw/mini-schedule/backend/internal/application/entitlement"
	"github.com/zkw/mini-schedule/backend/internal/application/learner"
	"github.com/zkw/mini-schedule/backend/internal/application/location"
	"github.com/zkw/mini-schedule/backend/internal/application/locationresource"
	"github.com/zkw/mini-schedule/backend/internal/application/onboarding"
	rbac2 "github.com/zkw/mini-schedule/backend/internal/application/rbac"
	"github.com/zkw/mini-schedule/backend/internal/application/recurringschedule"
	"github.com/zkw/mini-schedule/backend/internal/application/staff"
	"github.com/zkw/mini-schedule/backend/internal/application/training"
	"github.com/zkw/mini-schedule/backend/internal/application/user"
	"github.com/zkw/mini-schedule/backend/internal/domain/rbac"
	"github.com/zkw/mini-schedule/backend/internal/infrastructure/cache"
	"github.com/zkw/mini-schedule/backend/internal/infrastructure/config"
	"github.com/zkw/mini-schedule/backend/internal/infrastructure/payment"
	"github.com/zkw/mini-schedule/backend/internal/infrastructure/persistence"
	"github.com/zkw/mini-schedule/backend/internal/interfaces/admin"
	brand2 "github.com/zkw/mini-schedule/backend/internal/interfaces/brand"
	"github.com/zkw/mini-schedule/backend/internal/interfaces/middleware"
	"gorm.io/gorm"
	"log/slog"
)

import (
	_ "github.com/zkw/mini-schedule/backend/docs/brand"
)

// Injectors from wire.go:

// initializeBrandApp 品牌端依赖注入
func initializeBrandApp(cfg *config.Config, log *slog.Logger) (*gin.Engine, func(), error) {
	databaseConfig := provideDatabaseConfig(cfg)
	db, err := persistence.NewDatabase(databaseConfig, log)
	if err != nil {
		return nil, nil, err
	}
	repository := persistence.NewBrandRepository(db)
	service := brand.NewService(repository, cfg)
	brandUserRepository := persistence.NewBrandUserRepository(db)
	jwtConfig := provideJWTConfig(cfg)
	cacheService := cache.NewService(jwtConfig)
	brandUserService := user.NewBrandUserService(brandUserRepository, cacheService, log, cfg)
	appUserRepository := persistence.NewAppUserRepository(db)
	appUserService := user.NewAppUserService(appUserRepository, cfg)
	trainingRepository := persistence.NewTrainingRepository(db)
	trainingService := training.NewService(trainingRepository, cfg)
	onboardingRepository := persistence.NewOnboardingRepository(db)
	rbacRepository := persistence.NewRBACRepository(db)
	redisConfig := provideRedisConfig(cfg)
	client, err := cache.NewRedisClient(redisConfig, log)
	if err != nil {
		return nil, nil, err
	}
	checker, err := provideRBACChecker(rbacRepository, client, log)
	if err != nil {
		return nil, nil, err
	}
	onboardingService := onboarding.NewService(onboardingRepository, checker)
	onboardingHandler := brand2.NewOnboardingHandler(onboardingService)
	brandProfileRepository := persistence.NewBrandProfileRepository(db)
	brandprofileService := brandprofile.NewService(brandProfileRepository, checker)
	profileHandler := brand2.NewProfileHandler(brandprofileService)
	subscriptionGuard := commercial.NewSubscriptionGuard()
	locationRepository := persistence.NewLocationRepository(db, subscriptionGuard)
	locationService := location.NewService(locationRepository, checker)
	locationHandler := brand2.NewLocationHandler(locationService)
	staffRepository := persistence.NewStaffRepository(db, subscriptionGuard)
	roleRepository := persistence.NewRoleRepository(db)
	instructorRepository := persistence.NewInstructorRepository(db)
	staffService := staff.NewService(staffRepository, roleRepository, instructorRepository, checker)
	staffHandler := brand2.NewStaffHandler(staffService)
	meHandler := brand2.NewMeHandler(checker)
	coursecategoryRepository := persistence.NewCourseCategoryRepository(db)
	coursecategoryService := coursecategory.NewService(coursecategoryRepository, checker)
	courseCategoryHandler := brand2.NewCourseCategoryHandler(coursecategoryService)
	coursetemplateRepository := persistence.NewCourseTemplateRepository(db)
	coursetemplateService := coursetemplate.NewService(coursetemplateRepository, checker)
	courseTemplateHandler := brand2.NewCourseTemplateHandler(coursetemplateService)
	classsessionRepository := persistence.NewClassSessionRepository(db)
	classsessionService := classsession.NewService(classsessionRepository, checker)
	classSessionHandler := brand2.NewClassSessionHandler(classsessionService)
	locationresourceRepository := persistence.NewLocationResourceRepository(db)
	locationresourceService := locationresource.NewService(locationresourceRepository, checker)
	locationResourceHandler := brand2.NewLocationResourceHandler(locationresourceService)
	recurringscheduleRepository := persistence.NewRecurringScheduleRepository(db)
	recurringscheduleService := recurringschedule.NewService(recurringscheduleRepository, checker)
	recurringScheduleHandler := brand2.NewRecurringScheduleHandler(recurringscheduleService)
	learnerRepository := persistence.NewLearnerRepository(db, subscriptionGuard)
	learnerService := learner.NewService(learnerRepository, checker)
	learnerHandler := brand2.NewLearnerHandler(learnerService)
	entitlementRepository := persistence.NewEntitlementRepository(db)
	entitlementService := entitlement.NewService(entitlementRepository, checker)
	entitlementHandler := brand2.NewEntitlementHandler(entitlementService)
	bookingRepository := persistence.NewBookingRepository(db)
	bookingService := booking.NewService(bookingRepository, checker)
	bookingHandler := brand2.NewBookingHandler(bookingService)
	handler := brand2.NewHandler(service, brandUserService, appUserService, trainingService, cacheService, onboardingHandler, profileHandler, locationHandler, staffHandler, meHandler, courseCategoryHandler, courseTemplateHandler, classSessionHandler, locationResourceHandler, recurringScheduleHandler, learnerHandler, entitlementHandler, bookingHandler)
	commercialRepository := persistence.NewCommercialRepository(db)
	weChatPaymentAdapter := payment.NewWeChatPaymentAdapter(cfg)
	commercialService := commercial.NewService(commercialRepository, cfg, client, weChatPaymentAdapter)
	adminHandler := providePublicHandler(commercialService)
	roleAllocator := staff.NewRoleAllocator(roleRepository, db)
	engine := newBrandRouter(handler, adminHandler, commercialService, roleAllocator, db, client, cacheService, cfg, log)
	return engine, func() {
	}, nil
}

// wire.go:

// provideRBACChecker 把 Redis client 包成 cacheStore + 注入 log，给 *rbac.Checker。
// 各 service 的本地 PermissionChecker 接口在 wire.Build 里通过 wire.Bind 桥接到这一个 *rbac.Checker。
func provideRBACChecker(repo rbac.Repository, redisClient *redis.Client, log *slog.Logger) (*rbac2.Checker, error) {
	return rbac2.NewChecker(repo, rbac2.NewRedisCacheStore(redisClient), log)
}

// providePublicHandler 在 brand 进程内复用 admin.Handler 的 RegisterPublicRoutes。
//
// 受 backend/.learnings deep dive 提醒，这里 brand/admin 的 NewHandler 是不同签名，
// 直接用 admin.NewHandler 需要传 brand.Service / admin user service 等不属于 brand 端语义的
// 依赖（之前 wire_gen 把它们注入了 nil）。本 provider 集中容纳这层适配，方便后续重构成
// 独立 PublicHandler。
func providePublicHandler(commercialSvc *commercial.Service) *admin.Handler {
	return admin.NewHandler(nil, commercialSvc, nil, nil, nil)
}

// Provider 函数：从 Config 提取子配置
func provideDatabaseConfig(cfg *config.Config) *config.DatabaseConfig {
	return &cfg.Database
}

func provideRedisConfig(cfg *config.Config) *config.RedisConfig {
	return &cfg.Redis
}

func provideJWTConfig(cfg *config.Config) *config.JWTConfig {
	return &cfg.JWT
}

func newBrandRouter(
	h *brand2.Handler,
	ph *admin.Handler,
	commercialSvc *commercial.Service,
	roleAllocator *staff.RoleAllocator,
	db *gorm.DB,
	redisClient *redis.Client,
	jwtSvc *cache.Service,
	cfg *config.Config,
	log *slog.Logger,
) *gin.Engine {

	if commercialSvc != nil && roleAllocator != nil {
		commercialSvc.SetOwnerRoleAllocator(roleAllocator)
	}
	gin.SetMode(gin.ReleaseMode)
	if cfg.App.Debug {
		gin.SetMode(gin.DebugMode)
	}

	r := gin.New()
	r.Use(middleware.CORS(cfg.CORS))
	r.Use(middleware.Locale())
	r.Use(gin.Recovery())

	publicAPI := r.Group("/api/v1/public")
	ph.RegisterPublicRoutes(publicAPI)

	api := r.Group("/api/v1/brand")
	h.RegisterRoutes(api)

	return r
}
