// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"
	"github.com/zkw/mini-schedule/backend/internal/application/brand"
	commercialapp "github.com/zkw/mini-schedule/backend/internal/application/commercial"
	"github.com/zkw/mini-schedule/backend/internal/application/course"
	"github.com/zkw/mini-schedule/backend/internal/application/training"
	"github.com/zkw/mini-schedule/backend/internal/application/user"
	"github.com/zkw/mini-schedule/backend/internal/infrastructure/cache"
	"github.com/zkw/mini-schedule/backend/internal/infrastructure/config"
	"github.com/zkw/mini-schedule/backend/internal/infrastructure/payment"
	"github.com/zkw/mini-schedule/backend/internal/infrastructure/persistence"
	adminHandler "github.com/zkw/mini-schedule/backend/internal/interfaces/admin"
	brand2 "github.com/zkw/mini-schedule/backend/internal/interfaces/brand"
	"github.com/zkw/mini-schedule/backend/internal/interfaces/middleware"
	"gorm.io/gorm"
	"log/slog"
)

// Injectors from wire.go:

// initializeBrandApp 品牌端依赖注入
func initializeBrandApp(cfg *config.Config, log *slog.Logger) (*gin.Engine, func(), error) {
	databaseConfig := provideDatabaseConfig(cfg)
	db, err := persistence.NewDatabase(databaseConfig, log)
	if err != nil {
		return nil, nil, err
	}
	repository := persistence.NewBrandRepository(db)
	service := brand.NewService(repository, cfg)
	brandUserRepository := persistence.NewBrandUserRepository(db)
	jwtConfig := provideJWTConfig(cfg)
	cacheService := cache.NewService(jwtConfig)
	brandUserService := user.NewBrandUserService(brandUserRepository, cacheService, log, cfg)
	appUserRepository := persistence.NewAppUserRepository(db)
	appUserService := user.NewAppUserService(appUserRepository, cfg)
	courseRepository := persistence.NewCourseRepository(db)
	courseService := course.NewService(courseRepository, cfg)
	trainingRepository := persistence.NewTrainingRepository(db)
	trainingService := training.NewService(trainingRepository, cfg)
	handler := brand2.NewHandler(service, brandUserService, appUserService, courseService, trainingService, cacheService)
	commercialRepository := persistence.NewCommercialRepository(db)
	redisConfig := provideRedisConfig(cfg)
	client, err := cache.NewRedisClient(redisConfig, log)
	if err != nil {
		return nil, nil, err
	}
	// TODO wire regen: 微信支付 adapter 已加入 commercial.Service，请运行 `go generate ./...`
	wechatAdapter := payment.NewWeChatPaymentAdapter(cfg)
	commercialSvc := commercialapp.NewService(commercialRepository, cfg, client, wechatAdapter)
	publicHandler := adminHandler.NewHandler(nil, commercialSvc, nil, nil)
	engine := newBrandRouter(handler, publicHandler, db, client, cacheService, cfg, log)
	return engine, func() {
	}, nil
}

// wire.go:

// Provider 函数：从 Config 提取子配置
func provideDatabaseConfig(cfg *config.Config) *config.DatabaseConfig {
	return &cfg.Database
}

func provideRedisConfig(cfg *config.Config) *config.RedisConfig {
	return &cfg.Redis
}

func provideJWTConfig(cfg *config.Config) *config.JWTConfig {
	return &cfg.JWT
}

func newBrandRouter(
	h *brand2.Handler,
	ph *adminHandler.Handler,
	db *gorm.DB,
	redisClient *redis.Client,
	jwtSvc *cache.Service,
	cfg *config.Config,
	log *slog.Logger,
) *gin.Engine {
	gin.SetMode(gin.ReleaseMode)
	if cfg.App.Debug {
		gin.SetMode(gin.DebugMode)
	}

	r := gin.New()
	r.Use(middleware.CORS(cfg.CORS))
	r.Use(middleware.Locale())
	r.Use(gin.Recovery())

	publicAPI := r.Group("/api/v1/public")
	ph.RegisterPublicRoutes(publicAPI)

	api := r.Group("/api/v1/brand")
	h.RegisterRoutes(api)

	return r
}
